### ISSUE TITLE
Exact Match for Window titles you want TypingAid disabled for

### ISSUE THREAD

**Issue by Theclaws** [ManiacDC/TypingAid#43]
Currently the preference setting: 'Window titles you want TypingAid disabled for' (SQL Version) or 'ExcludeProgramTitles' (v2.19.9) operates by searching for the value as a substring.  

Suggest adding a 'ExcludeProgramTitlesExact' entry that allows to match titles exactly.  This would allow for the exclusion of windows with small titles (like the 'Run' window) without accidentally matching too many other windows.

**Comment by ManiacDC** [comment]
How about this?
If the Title is in enquoted, it's an exact match; otherwise it's the current contains match?

**Comment by Theclaws** [comment]
Elegant.  I like it!

Being the devil's advocate now: I've rarely seen it but what if the caption has a quote in it?

**Comment by ManiacDC** [comment]
I've coded this functionality:
https://github.com/ManiacDC/TypingAid/commit/e48b3ba12c739a13ce94f0d9d9301d7e8b7f7637

I thought about the issue of the Window Title having quotes in it. It will actually only matter if you want to have that quote as the beginning and end of a contains string. The algorithm is as follows:
If the first character and the last character of the string are double quotes, then strip them and exact match.
Otherwise, just do a contains match.

**Comment by Theclaws** [comment]
Works great!  I would considered this enhancement request completed and closed.

**Comment by ManiacDC** [comment]
https://github.com/ManiacDC/TypingAid/releases/tag/v2.22.0.0
