### ISSUE TITLE
Typing Aid & Ditto

### ISSUE THREAD

**Issue by Judykator** [ManiacDC/TypingAid#79]
I use Typing Aid & Ditto.
Until now, I used TypingAid 2.15. 
1) I press "ctrl+`" and open Ditto searach windows. 
2) I wrote a search word. 
3) After three letters appears TypingAid window. 
4) Using the numbers (press number) I chose a word that interceded for the search window ditto. [for example i type "War" press 1 paste "Warsow" Everything worked.

Now I launched TypingAid 2.22. And it works differently.
1) I press "ctrl+`" and open Ditto searach windows. 
2) I wrote a search word. 
3) After three letters appears TypingAid window. 
4) Using the numbers (press number) ... now TypingAid 2.22 does not insert the word. Instead of the word in the search window appears selected number [for example - i type ""War" press 1 and instead "Warsow" i have "War1" ?? 

Why is this happening? I changed only version TypingAid. I can do to version 2.22 work as well as version 2.15 with program Ditto (https://sourceforge.net/projects/ditto-cp/).

I will add that I tried all methods of insertion (fast/slow typing or pasting)

**Comment by ManiacDC** [comment]
1. Does this only happen in ditto, or does it happen in notepad also?
2. Can I assume you are using the numbers at the top of the keyboard and NOT the number pad?
3. Under Settings > General Settings > Auto-Complete Keys, is there a checkmark next to "Number Keys"?

**Comment by Judykator** [comment]
1. in ditto only. I use Word, Libre Office or Firefox and there is fine. 
2. I use numbers at the top of the keyboard, don`t use number pad
3. yes. I checkmarked all.

I use now Typing Aid 2.20 & Ditto and is fine.

**Comment by ManiacDC** [comment]
So... it's working now?

**Comment by Judykator** [comment]
Yes. v. 2.20 + Ditto works well.

**Comment by ManiacDC** [comment]
Does 2.21.1 work? I would guess 2.21/2.21.1 is where it stopped working.

**Comment by Judykator** [comment]
2.21.0 or 2.21.1 not work with Ditto
Before I press "1"
https://www.dropbox.com/s/904pqxaqksthfkw/before1.png?dl=0
Atter I press "1"
https://www.dropbox.com/s/7dxa7ifyiikmr4c/after1.png?dl=0

**Comment by ManiacDC** [comment]
So I tested this out and figured out what's happening. In TypingAid 2.21, I check more frequently to make sure we're still in the "current window" AND the same working context when actually going to send the word. To determine this, I check (and always have) that the Window ID *AND* Window Title match. This is important because if I switch documents in a program, I don't want my TypingAid ListBox carrying over as we are no longer in the same document! This happened in 2.20 also, just not as often (and I was able to reproduce this issue in 2.20, just less often).

The problem with Ditto is that it updates the Window Title every time the number of matches changes. This doesn't work well with TypingAid. There are a few options:
1. Simply customize your copy of ReturnWinActive() in Window.ahk:
Change the line:
Return, (( g_Active_Id == Temp_id ) && ( Last_Title == Temp_Title ))
to:
Return, ( g_Active_Id == Temp_id )
Note, this will have the side effect of making it so that changing documents in a text/document editor or tabs in some browsers may not close the listbox.

2. We can create a new issue to exclude checking the title for user-defined programs.

3. You can ask the Ditto developer for an option to *not* display the number of matches in the Window Title.

Let me know your thoughts... thanks!

**Comment by Judykator** [comment]
Hi, thanks for the help
I am an amateur and I only use the compiled script. I could not change anything inside the program. I ask yet forum Ditto but it probably will not do anything.

If you could do for me an improved compiled script is willing to try to use it. Maybe in the next version TypingAid You change something. For now, I will be using version 2.20

Although interesting for me looks possibility of replace (...|r|...) t would be nice to add a keyboard shortcut

**Comment by Judykator** [comment]
Ditto autor update Ditto to not change the window title and just use a custom variable for displaying the title text..  (https://sourceforge.net/p/ditto-cp/discussion/287511/thread/63f83459/)
but behavior version not change. (I use DittoPortable_3_21_79_0)

**Comment by ManiacDC** [comment]
3.21.80.0 fixes the issue, I just tried it.

http://ditto-cp.sourceforge.net/beta/

**Comment by Judykator** [comment]
OK. Ditto 3.21.80 & TypinAid 2.22 works. Thanks

**Comment by ManiacDC** [comment]
OK, thanks!
